included: # paths to include during linting. `--path` is ignored if present.
  - Sources
# parameterized rules can be customized from this configuration file
line_length: 120
# parameterized rules are first parameterized as a warning level, then error level.
type_body_length:
  - 300 # warning
  - 400 # error
